### PR TITLE
Fix #21 : set slf4j dependency to scope test

### LINKED ISSUE #21: slf4j dependency is only required by a Test : change scope to test in pom.xml
https://github.com/conversant/disruptor/blob/7f3c0331ce010cbbc29df2791c57024896bede28/pom.xml#L235

I had a look from GeoTools project perspective an was wondering why slf4j is in dependency but not referenced in any runtime class.

This leads to dependency conflicts in downstream projects and could easily fixed be adding scope test

### PR DESCRIPTION
**Pull request by fgdrf**
Signed-off-by: Frank Gasdorf <fgdrf@users.sourceforge.net>

### CODE REVIEW

**Review by jac18281828 — APPROVED** [review]
Thanks!  This is a very helpful improvement and something I should have noticed myself.

**Comment by fgdrf** [comment]
You are welcome, I run the build locally and it works fine. Do you have a build job that verifies changes?

**Comment by fgdrf** [comment]
w is the procedure to get it merged?

**Comment by jac18281828** [comment]
I just merged the ci pull request.   I took care of clicking merge for you! Thanks again!

**Pull request merged**
